name: Deploiement Contabo

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copier les fichiers vers Contabo
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USER }}
          key: ${{ secrets.CONTABO_SSH_KEY }}
          source: "."
          target: "/home/value/ComIntValue-it"

      - name: Build et redemarrge Docker
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.CONTABO_HOST }}
          username: ${{ secrets.CONTABO_USER }}
          key: ${{ secrets.CONTABO_SSH_KEY }}
          command_timeout: 30m
          script: |
            cd /home/value/ComIntValue-it
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build